[package]
name = "tree-sitter-javascript"
version = "0.1.0"
authors = ["Max Brunsfeld <maxbrunsfeld@gmail.com>"]
edition = "2018"

[dependencies]
tree-sitter = "0.3.10"

[build-dependencies]
cc = "1.0"